
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Astronauts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Astronauts
 * 
 */
export type AstronautsModel = runtime.Types.Result.DefaultSelection<Prisma.$AstronautsPayload>

export type AggregateAstronauts = {
  _count: AstronautsCountAggregateOutputType | null
  _avg: AstronautsAvgAggregateOutputType | null
  _sum: AstronautsSumAggregateOutputType | null
  _min: AstronautsMinAggregateOutputType | null
  _max: AstronautsMaxAggregateOutputType | null
}

export type AstronautsAvgAggregateOutputType = {
  rating: number | null
  price: number | null
}

export type AstronautsSumAggregateOutputType = {
  rating: number | null
  price: number | null
}

export type AstronautsMinAggregateOutputType = {
  name: string | null
  rating: number | null
  price: number | null
  modelUrl: string | null
  shopIconUrl: string | null
  isEngineer: boolean | null
  isResearcher: boolean | null
  isPilot: boolean | null
  hiddenOnLock: boolean | null
}

export type AstronautsMaxAggregateOutputType = {
  name: string | null
  rating: number | null
  price: number | null
  modelUrl: string | null
  shopIconUrl: string | null
  isEngineer: boolean | null
  isResearcher: boolean | null
  isPilot: boolean | null
  hiddenOnLock: boolean | null
}

export type AstronautsCountAggregateOutputType = {
  name: number
  rating: number
  price: number
  modelUrl: number
  shopIconUrl: number
  isEngineer: number
  isResearcher: number
  isPilot: number
  hiddenOnLock: number
  _all: number
}


export type AstronautsAvgAggregateInputType = {
  rating?: true
  price?: true
}

export type AstronautsSumAggregateInputType = {
  rating?: true
  price?: true
}

export type AstronautsMinAggregateInputType = {
  name?: true
  rating?: true
  price?: true
  modelUrl?: true
  shopIconUrl?: true
  isEngineer?: true
  isResearcher?: true
  isPilot?: true
  hiddenOnLock?: true
}

export type AstronautsMaxAggregateInputType = {
  name?: true
  rating?: true
  price?: true
  modelUrl?: true
  shopIconUrl?: true
  isEngineer?: true
  isResearcher?: true
  isPilot?: true
  hiddenOnLock?: true
}

export type AstronautsCountAggregateInputType = {
  name?: true
  rating?: true
  price?: true
  modelUrl?: true
  shopIconUrl?: true
  isEngineer?: true
  isResearcher?: true
  isPilot?: true
  hiddenOnLock?: true
  _all?: true
}

export type AstronautsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Astronauts to aggregate.
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Astronauts to fetch.
   */
  orderBy?: Prisma.AstronautsOrderByWithRelationInput | Prisma.AstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Astronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Astronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Astronauts
  **/
  _count?: true | AstronautsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AstronautsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AstronautsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AstronautsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AstronautsMaxAggregateInputType
}

export type GetAstronautsAggregateType<T extends AstronautsAggregateArgs> = {
      [P in keyof T & keyof AggregateAstronauts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAstronauts[P]>
    : Prisma.GetScalarType<T[P], AggregateAstronauts[P]>
}




export type AstronautsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AstronautsWhereInput
  orderBy?: Prisma.AstronautsOrderByWithAggregationInput | Prisma.AstronautsOrderByWithAggregationInput[]
  by: Prisma.AstronautsScalarFieldEnum[] | Prisma.AstronautsScalarFieldEnum
  having?: Prisma.AstronautsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AstronautsCountAggregateInputType | true
  _avg?: AstronautsAvgAggregateInputType
  _sum?: AstronautsSumAggregateInputType
  _min?: AstronautsMinAggregateInputType
  _max?: AstronautsMaxAggregateInputType
}

export type AstronautsGroupByOutputType = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock: boolean
  _count: AstronautsCountAggregateOutputType | null
  _avg: AstronautsAvgAggregateOutputType | null
  _sum: AstronautsSumAggregateOutputType | null
  _min: AstronautsMinAggregateOutputType | null
  _max: AstronautsMaxAggregateOutputType | null
}

type GetAstronautsGroupByPayload<T extends AstronautsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AstronautsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AstronautsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AstronautsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AstronautsGroupByOutputType[P]>
      }
    >
  >



export type AstronautsWhereInput = {
  AND?: Prisma.AstronautsWhereInput | Prisma.AstronautsWhereInput[]
  OR?: Prisma.AstronautsWhereInput[]
  NOT?: Prisma.AstronautsWhereInput | Prisma.AstronautsWhereInput[]
  name?: Prisma.StringFilter<"Astronauts"> | string
  rating?: Prisma.IntFilter<"Astronauts"> | number
  price?: Prisma.IntFilter<"Astronauts"> | number
  modelUrl?: Prisma.StringFilter<"Astronauts"> | string
  shopIconUrl?: Prisma.StringFilter<"Astronauts"> | string
  isEngineer?: Prisma.BoolFilter<"Astronauts"> | boolean
  isResearcher?: Prisma.BoolFilter<"Astronauts"> | boolean
  isPilot?: Prisma.BoolFilter<"Astronauts"> | boolean
  hiddenOnLock?: Prisma.BoolFilter<"Astronauts"> | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsListRelationFilter
  unlockedAstronauts?: Prisma.UnlockedAstronautsListRelationFilter
}

export type AstronautsOrderByWithRelationInput = {
  name?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
  modelUrl?: Prisma.SortOrder
  shopIconUrl?: Prisma.SortOrder
  isEngineer?: Prisma.SortOrder
  isResearcher?: Prisma.SortOrder
  isPilot?: Prisma.SortOrder
  hiddenOnLock?: Prisma.SortOrder
  ownedAstronauts?: Prisma.OwnedAstronautsOrderByRelationAggregateInput
  unlockedAstronauts?: Prisma.UnlockedAstronautsOrderByRelationAggregateInput
}

export type AstronautsWhereUniqueInput = Prisma.AtLeast<{
  name?: string
  AND?: Prisma.AstronautsWhereInput | Prisma.AstronautsWhereInput[]
  OR?: Prisma.AstronautsWhereInput[]
  NOT?: Prisma.AstronautsWhereInput | Prisma.AstronautsWhereInput[]
  rating?: Prisma.IntFilter<"Astronauts"> | number
  price?: Prisma.IntFilter<"Astronauts"> | number
  modelUrl?: Prisma.StringFilter<"Astronauts"> | string
  shopIconUrl?: Prisma.StringFilter<"Astronauts"> | string
  isEngineer?: Prisma.BoolFilter<"Astronauts"> | boolean
  isResearcher?: Prisma.BoolFilter<"Astronauts"> | boolean
  isPilot?: Prisma.BoolFilter<"Astronauts"> | boolean
  hiddenOnLock?: Prisma.BoolFilter<"Astronauts"> | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsListRelationFilter
  unlockedAstronauts?: Prisma.UnlockedAstronautsListRelationFilter
}, "name">

export type AstronautsOrderByWithAggregationInput = {
  name?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
  modelUrl?: Prisma.SortOrder
  shopIconUrl?: Prisma.SortOrder
  isEngineer?: Prisma.SortOrder
  isResearcher?: Prisma.SortOrder
  isPilot?: Prisma.SortOrder
  hiddenOnLock?: Prisma.SortOrder
  _count?: Prisma.AstronautsCountOrderByAggregateInput
  _avg?: Prisma.AstronautsAvgOrderByAggregateInput
  _max?: Prisma.AstronautsMaxOrderByAggregateInput
  _min?: Prisma.AstronautsMinOrderByAggregateInput
  _sum?: Prisma.AstronautsSumOrderByAggregateInput
}

export type AstronautsScalarWhereWithAggregatesInput = {
  AND?: Prisma.AstronautsScalarWhereWithAggregatesInput | Prisma.AstronautsScalarWhereWithAggregatesInput[]
  OR?: Prisma.AstronautsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AstronautsScalarWhereWithAggregatesInput | Prisma.AstronautsScalarWhereWithAggregatesInput[]
  name?: Prisma.StringWithAggregatesFilter<"Astronauts"> | string
  rating?: Prisma.IntWithAggregatesFilter<"Astronauts"> | number
  price?: Prisma.IntWithAggregatesFilter<"Astronauts"> | number
  modelUrl?: Prisma.StringWithAggregatesFilter<"Astronauts"> | string
  shopIconUrl?: Prisma.StringWithAggregatesFilter<"Astronauts"> | string
  isEngineer?: Prisma.BoolWithAggregatesFilter<"Astronauts"> | boolean
  isResearcher?: Prisma.BoolWithAggregatesFilter<"Astronauts"> | boolean
  isPilot?: Prisma.BoolWithAggregatesFilter<"Astronauts"> | boolean
  hiddenOnLock?: Prisma.BoolWithAggregatesFilter<"Astronauts"> | boolean
}

export type AstronautsCreateInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  ownedAstronauts?: Prisma.OwnedAstronautsCreateNestedManyWithoutAstronautDataInput
  unlockedAstronauts?: Prisma.UnlockedAstronautsCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsUncheckedCreateInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput
  unlockedAstronauts?: Prisma.UnlockedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUpdateManyWithoutAstronautDataNestedInput
  unlockedAstronauts?: Prisma.UnlockedAstronautsUpdateManyWithoutAstronautDataNestedInput
}

export type AstronautsUncheckedUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput
  unlockedAstronauts?: Prisma.UnlockedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput
}

export type AstronautsCreateManyInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
}

export type AstronautsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AstronautsUncheckedUpdateManyInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AstronautsScalarRelationFilter = {
  is?: Prisma.AstronautsWhereInput
  isNot?: Prisma.AstronautsWhereInput
}

export type AstronautsCountOrderByAggregateInput = {
  name?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
  modelUrl?: Prisma.SortOrder
  shopIconUrl?: Prisma.SortOrder
  isEngineer?: Prisma.SortOrder
  isResearcher?: Prisma.SortOrder
  isPilot?: Prisma.SortOrder
  hiddenOnLock?: Prisma.SortOrder
}

export type AstronautsAvgOrderByAggregateInput = {
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type AstronautsMaxOrderByAggregateInput = {
  name?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
  modelUrl?: Prisma.SortOrder
  shopIconUrl?: Prisma.SortOrder
  isEngineer?: Prisma.SortOrder
  isResearcher?: Prisma.SortOrder
  isPilot?: Prisma.SortOrder
  hiddenOnLock?: Prisma.SortOrder
}

export type AstronautsMinOrderByAggregateInput = {
  name?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
  modelUrl?: Prisma.SortOrder
  shopIconUrl?: Prisma.SortOrder
  isEngineer?: Prisma.SortOrder
  isResearcher?: Prisma.SortOrder
  isPilot?: Prisma.SortOrder
  hiddenOnLock?: Prisma.SortOrder
}

export type AstronautsSumOrderByAggregateInput = {
  rating?: Prisma.SortOrder
  price?: Prisma.SortOrder
}

export type AstronautsCreateNestedOneWithoutOwnedAstronautsInput = {
  create?: Prisma.XOR<Prisma.AstronautsCreateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutOwnedAstronautsInput>
  connectOrCreate?: Prisma.AstronautsCreateOrConnectWithoutOwnedAstronautsInput
  connect?: Prisma.AstronautsWhereUniqueInput
}

export type AstronautsUpdateOneRequiredWithoutOwnedAstronautsNestedInput = {
  create?: Prisma.XOR<Prisma.AstronautsCreateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutOwnedAstronautsInput>
  connectOrCreate?: Prisma.AstronautsCreateOrConnectWithoutOwnedAstronautsInput
  upsert?: Prisma.AstronautsUpsertWithoutOwnedAstronautsInput
  connect?: Prisma.AstronautsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AstronautsUpdateToOneWithWhereWithoutOwnedAstronautsInput, Prisma.AstronautsUpdateWithoutOwnedAstronautsInput>, Prisma.AstronautsUncheckedUpdateWithoutOwnedAstronautsInput>
}

export type AstronautsCreateNestedOneWithoutUnlockedAstronautsInput = {
  create?: Prisma.XOR<Prisma.AstronautsCreateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutUnlockedAstronautsInput>
  connectOrCreate?: Prisma.AstronautsCreateOrConnectWithoutUnlockedAstronautsInput
  connect?: Prisma.AstronautsWhereUniqueInput
}

export type AstronautsUpdateOneRequiredWithoutUnlockedAstronautsNestedInput = {
  create?: Prisma.XOR<Prisma.AstronautsCreateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutUnlockedAstronautsInput>
  connectOrCreate?: Prisma.AstronautsCreateOrConnectWithoutUnlockedAstronautsInput
  upsert?: Prisma.AstronautsUpsertWithoutUnlockedAstronautsInput
  connect?: Prisma.AstronautsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AstronautsUpdateToOneWithWhereWithoutUnlockedAstronautsInput, Prisma.AstronautsUpdateWithoutUnlockedAstronautsInput>, Prisma.AstronautsUncheckedUpdateWithoutUnlockedAstronautsInput>
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type AstronautsCreateWithoutOwnedAstronautsInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  unlockedAstronauts?: Prisma.UnlockedAstronautsCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsUncheckedCreateWithoutOwnedAstronautsInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  unlockedAstronauts?: Prisma.UnlockedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsCreateOrConnectWithoutOwnedAstronautsInput = {
  where: Prisma.AstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.AstronautsCreateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutOwnedAstronautsInput>
}

export type AstronautsUpsertWithoutOwnedAstronautsInput = {
  update: Prisma.XOR<Prisma.AstronautsUpdateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedUpdateWithoutOwnedAstronautsInput>
  create: Prisma.XOR<Prisma.AstronautsCreateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutOwnedAstronautsInput>
  where?: Prisma.AstronautsWhereInput
}

export type AstronautsUpdateToOneWithWhereWithoutOwnedAstronautsInput = {
  where?: Prisma.AstronautsWhereInput
  data: Prisma.XOR<Prisma.AstronautsUpdateWithoutOwnedAstronautsInput, Prisma.AstronautsUncheckedUpdateWithoutOwnedAstronautsInput>
}

export type AstronautsUpdateWithoutOwnedAstronautsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unlockedAstronauts?: Prisma.UnlockedAstronautsUpdateManyWithoutAstronautDataNestedInput
}

export type AstronautsUncheckedUpdateWithoutOwnedAstronautsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unlockedAstronauts?: Prisma.UnlockedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput
}

export type AstronautsCreateWithoutUnlockedAstronautsInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  ownedAstronauts?: Prisma.OwnedAstronautsCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsUncheckedCreateWithoutUnlockedAstronautsInput = {
  name: string
  rating: number
  price: number
  modelUrl: string
  shopIconUrl: string
  isEngineer: boolean
  isResearcher: boolean
  isPilot: boolean
  hiddenOnLock?: boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput
}

export type AstronautsCreateOrConnectWithoutUnlockedAstronautsInput = {
  where: Prisma.AstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.AstronautsCreateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutUnlockedAstronautsInput>
}

export type AstronautsUpsertWithoutUnlockedAstronautsInput = {
  update: Prisma.XOR<Prisma.AstronautsUpdateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedUpdateWithoutUnlockedAstronautsInput>
  create: Prisma.XOR<Prisma.AstronautsCreateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedCreateWithoutUnlockedAstronautsInput>
  where?: Prisma.AstronautsWhereInput
}

export type AstronautsUpdateToOneWithWhereWithoutUnlockedAstronautsInput = {
  where?: Prisma.AstronautsWhereInput
  data: Prisma.XOR<Prisma.AstronautsUpdateWithoutUnlockedAstronautsInput, Prisma.AstronautsUncheckedUpdateWithoutUnlockedAstronautsInput>
}

export type AstronautsUpdateWithoutUnlockedAstronautsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUpdateManyWithoutAstronautDataNestedInput
}

export type AstronautsUncheckedUpdateWithoutUnlockedAstronautsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.IntFieldUpdateOperationsInput | number
  price?: Prisma.IntFieldUpdateOperationsInput | number
  modelUrl?: Prisma.StringFieldUpdateOperationsInput | string
  shopIconUrl?: Prisma.StringFieldUpdateOperationsInput | string
  isEngineer?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isResearcher?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isPilot?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hiddenOnLock?: Prisma.BoolFieldUpdateOperationsInput | boolean
  ownedAstronauts?: Prisma.OwnedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput
}


/**
 * Count Type AstronautsCountOutputType
 */

export type AstronautsCountOutputType = {
  ownedAstronauts: number
  unlockedAstronauts: number
}

export type AstronautsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownedAstronauts?: boolean | AstronautsCountOutputTypeCountOwnedAstronautsArgs
  unlockedAstronauts?: boolean | AstronautsCountOutputTypeCountUnlockedAstronautsArgs
}

/**
 * AstronautsCountOutputType without action
 */
export type AstronautsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AstronautsCountOutputType
   */
  select?: Prisma.AstronautsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AstronautsCountOutputType without action
 */
export type AstronautsCountOutputTypeCountOwnedAstronautsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OwnedAstronautsWhereInput
}

/**
 * AstronautsCountOutputType without action
 */
export type AstronautsCountOutputTypeCountUnlockedAstronautsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnlockedAstronautsWhereInput
}


export type AstronautsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  rating?: boolean
  price?: boolean
  modelUrl?: boolean
  shopIconUrl?: boolean
  isEngineer?: boolean
  isResearcher?: boolean
  isPilot?: boolean
  hiddenOnLock?: boolean
  ownedAstronauts?: boolean | Prisma.Astronauts$ownedAstronautsArgs<ExtArgs>
  unlockedAstronauts?: boolean | Prisma.Astronauts$unlockedAstronautsArgs<ExtArgs>
  _count?: boolean | Prisma.AstronautsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["astronauts"]>

export type AstronautsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  rating?: boolean
  price?: boolean
  modelUrl?: boolean
  shopIconUrl?: boolean
  isEngineer?: boolean
  isResearcher?: boolean
  isPilot?: boolean
  hiddenOnLock?: boolean
}, ExtArgs["result"]["astronauts"]>

export type AstronautsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  rating?: boolean
  price?: boolean
  modelUrl?: boolean
  shopIconUrl?: boolean
  isEngineer?: boolean
  isResearcher?: boolean
  isPilot?: boolean
  hiddenOnLock?: boolean
}, ExtArgs["result"]["astronauts"]>

export type AstronautsSelectScalar = {
  name?: boolean
  rating?: boolean
  price?: boolean
  modelUrl?: boolean
  shopIconUrl?: boolean
  isEngineer?: boolean
  isResearcher?: boolean
  isPilot?: boolean
  hiddenOnLock?: boolean
}

export type AstronautsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "rating" | "price" | "modelUrl" | "shopIconUrl" | "isEngineer" | "isResearcher" | "isPilot" | "hiddenOnLock", ExtArgs["result"]["astronauts"]>
export type AstronautsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  ownedAstronauts?: boolean | Prisma.Astronauts$ownedAstronautsArgs<ExtArgs>
  unlockedAstronauts?: boolean | Prisma.Astronauts$unlockedAstronautsArgs<ExtArgs>
  _count?: boolean | Prisma.AstronautsCountOutputTypeDefaultArgs<ExtArgs>
}
export type AstronautsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AstronautsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AstronautsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Astronauts"
  objects: {
    ownedAstronauts: Prisma.$OwnedAstronautsPayload<ExtArgs>[]
    unlockedAstronauts: Prisma.$UnlockedAstronautsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    name: string
    rating: number
    price: number
    modelUrl: string
    shopIconUrl: string
    isEngineer: boolean
    isResearcher: boolean
    isPilot: boolean
    hiddenOnLock: boolean
  }, ExtArgs["result"]["astronauts"]>
  composites: {}
}

export type AstronautsGetPayload<S extends boolean | null | undefined | AstronautsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AstronautsPayload, S>

export type AstronautsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AstronautsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AstronautsCountAggregateInputType | true
  }

export interface AstronautsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Astronauts'], meta: { name: 'Astronauts' } }
  /**
   * Find zero or one Astronauts that matches the filter.
   * @param {AstronautsFindUniqueArgs} args - Arguments to find a Astronauts
   * @example
   * // Get one Astronauts
   * const astronauts = await prisma.astronauts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AstronautsFindUniqueArgs>(args: Prisma.SelectSubset<T, AstronautsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Astronauts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AstronautsFindUniqueOrThrowArgs} args - Arguments to find a Astronauts
   * @example
   * // Get one Astronauts
   * const astronauts = await prisma.astronauts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AstronautsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AstronautsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Astronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsFindFirstArgs} args - Arguments to find a Astronauts
   * @example
   * // Get one Astronauts
   * const astronauts = await prisma.astronauts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AstronautsFindFirstArgs>(args?: Prisma.SelectSubset<T, AstronautsFindFirstArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Astronauts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsFindFirstOrThrowArgs} args - Arguments to find a Astronauts
   * @example
   * // Get one Astronauts
   * const astronauts = await prisma.astronauts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AstronautsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AstronautsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Astronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Astronauts
   * const astronauts = await prisma.astronauts.findMany()
   * 
   * // Get first 10 Astronauts
   * const astronauts = await prisma.astronauts.findMany({ take: 10 })
   * 
   * // Only select the `name`
   * const astronautsWithNameOnly = await prisma.astronauts.findMany({ select: { name: true } })
   * 
   */
  findMany<T extends AstronautsFindManyArgs>(args?: Prisma.SelectSubset<T, AstronautsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Astronauts.
   * @param {AstronautsCreateArgs} args - Arguments to create a Astronauts.
   * @example
   * // Create one Astronauts
   * const Astronauts = await prisma.astronauts.create({
   *   data: {
   *     // ... data to create a Astronauts
   *   }
   * })
   * 
   */
  create<T extends AstronautsCreateArgs>(args: Prisma.SelectSubset<T, AstronautsCreateArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Astronauts.
   * @param {AstronautsCreateManyArgs} args - Arguments to create many Astronauts.
   * @example
   * // Create many Astronauts
   * const astronauts = await prisma.astronauts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AstronautsCreateManyArgs>(args?: Prisma.SelectSubset<T, AstronautsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Astronauts and returns the data saved in the database.
   * @param {AstronautsCreateManyAndReturnArgs} args - Arguments to create many Astronauts.
   * @example
   * // Create many Astronauts
   * const astronauts = await prisma.astronauts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Astronauts and only return the `name`
   * const astronautsWithNameOnly = await prisma.astronauts.createManyAndReturn({
   *   select: { name: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AstronautsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AstronautsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Astronauts.
   * @param {AstronautsDeleteArgs} args - Arguments to delete one Astronauts.
   * @example
   * // Delete one Astronauts
   * const Astronauts = await prisma.astronauts.delete({
   *   where: {
   *     // ... filter to delete one Astronauts
   *   }
   * })
   * 
   */
  delete<T extends AstronautsDeleteArgs>(args: Prisma.SelectSubset<T, AstronautsDeleteArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Astronauts.
   * @param {AstronautsUpdateArgs} args - Arguments to update one Astronauts.
   * @example
   * // Update one Astronauts
   * const astronauts = await prisma.astronauts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AstronautsUpdateArgs>(args: Prisma.SelectSubset<T, AstronautsUpdateArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Astronauts.
   * @param {AstronautsDeleteManyArgs} args - Arguments to filter Astronauts to delete.
   * @example
   * // Delete a few Astronauts
   * const { count } = await prisma.astronauts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AstronautsDeleteManyArgs>(args?: Prisma.SelectSubset<T, AstronautsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Astronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Astronauts
   * const astronauts = await prisma.astronauts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AstronautsUpdateManyArgs>(args: Prisma.SelectSubset<T, AstronautsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Astronauts and returns the data updated in the database.
   * @param {AstronautsUpdateManyAndReturnArgs} args - Arguments to update many Astronauts.
   * @example
   * // Update many Astronauts
   * const astronauts = await prisma.astronauts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Astronauts and only return the `name`
   * const astronautsWithNameOnly = await prisma.astronauts.updateManyAndReturn({
   *   select: { name: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AstronautsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AstronautsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Astronauts.
   * @param {AstronautsUpsertArgs} args - Arguments to update or create a Astronauts.
   * @example
   * // Update or create a Astronauts
   * const astronauts = await prisma.astronauts.upsert({
   *   create: {
   *     // ... data to create a Astronauts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Astronauts we want to update
   *   }
   * })
   */
  upsert<T extends AstronautsUpsertArgs>(args: Prisma.SelectSubset<T, AstronautsUpsertArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Astronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsCountArgs} args - Arguments to filter Astronauts to count.
   * @example
   * // Count the number of Astronauts
   * const count = await prisma.astronauts.count({
   *   where: {
   *     // ... the filter for the Astronauts we want to count
   *   }
   * })
  **/
  count<T extends AstronautsCountArgs>(
    args?: Prisma.Subset<T, AstronautsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AstronautsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Astronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AstronautsAggregateArgs>(args: Prisma.Subset<T, AstronautsAggregateArgs>): Prisma.PrismaPromise<GetAstronautsAggregateType<T>>

  /**
   * Group by Astronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AstronautsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AstronautsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AstronautsGroupByArgs['orderBy'] }
      : { orderBy?: AstronautsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AstronautsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAstronautsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Astronauts model
 */
readonly fields: AstronautsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Astronauts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AstronautsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  ownedAstronauts<T extends Prisma.Astronauts$ownedAstronautsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Astronauts$ownedAstronautsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  unlockedAstronauts<T extends Prisma.Astronauts$unlockedAstronautsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Astronauts$unlockedAstronautsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Astronauts model
 */
export interface AstronautsFieldRefs {
  readonly name: Prisma.FieldRef<"Astronauts", 'String'>
  readonly rating: Prisma.FieldRef<"Astronauts", 'Int'>
  readonly price: Prisma.FieldRef<"Astronauts", 'Int'>
  readonly modelUrl: Prisma.FieldRef<"Astronauts", 'String'>
  readonly shopIconUrl: Prisma.FieldRef<"Astronauts", 'String'>
  readonly isEngineer: Prisma.FieldRef<"Astronauts", 'Boolean'>
  readonly isResearcher: Prisma.FieldRef<"Astronauts", 'Boolean'>
  readonly isPilot: Prisma.FieldRef<"Astronauts", 'Boolean'>
  readonly hiddenOnLock: Prisma.FieldRef<"Astronauts", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Astronauts findUnique
 */
export type AstronautsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter, which Astronauts to fetch.
   */
  where: Prisma.AstronautsWhereUniqueInput
}

/**
 * Astronauts findUniqueOrThrow
 */
export type AstronautsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter, which Astronauts to fetch.
   */
  where: Prisma.AstronautsWhereUniqueInput
}

/**
 * Astronauts findFirst
 */
export type AstronautsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter, which Astronauts to fetch.
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Astronauts to fetch.
   */
  orderBy?: Prisma.AstronautsOrderByWithRelationInput | Prisma.AstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Astronauts.
   */
  cursor?: Prisma.AstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Astronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Astronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Astronauts.
   */
  distinct?: Prisma.AstronautsScalarFieldEnum | Prisma.AstronautsScalarFieldEnum[]
}

/**
 * Astronauts findFirstOrThrow
 */
export type AstronautsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter, which Astronauts to fetch.
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Astronauts to fetch.
   */
  orderBy?: Prisma.AstronautsOrderByWithRelationInput | Prisma.AstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Astronauts.
   */
  cursor?: Prisma.AstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Astronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Astronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Astronauts.
   */
  distinct?: Prisma.AstronautsScalarFieldEnum | Prisma.AstronautsScalarFieldEnum[]
}

/**
 * Astronauts findMany
 */
export type AstronautsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter, which Astronauts to fetch.
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Astronauts to fetch.
   */
  orderBy?: Prisma.AstronautsOrderByWithRelationInput | Prisma.AstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Astronauts.
   */
  cursor?: Prisma.AstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Astronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Astronauts.
   */
  skip?: number
  distinct?: Prisma.AstronautsScalarFieldEnum | Prisma.AstronautsScalarFieldEnum[]
}

/**
 * Astronauts create
 */
export type AstronautsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * The data needed to create a Astronauts.
   */
  data: Prisma.XOR<Prisma.AstronautsCreateInput, Prisma.AstronautsUncheckedCreateInput>
}

/**
 * Astronauts createMany
 */
export type AstronautsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Astronauts.
   */
  data: Prisma.AstronautsCreateManyInput | Prisma.AstronautsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Astronauts createManyAndReturn
 */
export type AstronautsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * The data used to create many Astronauts.
   */
  data: Prisma.AstronautsCreateManyInput | Prisma.AstronautsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Astronauts update
 */
export type AstronautsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * The data needed to update a Astronauts.
   */
  data: Prisma.XOR<Prisma.AstronautsUpdateInput, Prisma.AstronautsUncheckedUpdateInput>
  /**
   * Choose, which Astronauts to update.
   */
  where: Prisma.AstronautsWhereUniqueInput
}

/**
 * Astronauts updateMany
 */
export type AstronautsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Astronauts.
   */
  data: Prisma.XOR<Prisma.AstronautsUpdateManyMutationInput, Prisma.AstronautsUncheckedUpdateManyInput>
  /**
   * Filter which Astronauts to update
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * Limit how many Astronauts to update.
   */
  limit?: number
}

/**
 * Astronauts updateManyAndReturn
 */
export type AstronautsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * The data used to update Astronauts.
   */
  data: Prisma.XOR<Prisma.AstronautsUpdateManyMutationInput, Prisma.AstronautsUncheckedUpdateManyInput>
  /**
   * Filter which Astronauts to update
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * Limit how many Astronauts to update.
   */
  limit?: number
}

/**
 * Astronauts upsert
 */
export type AstronautsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * The filter to search for the Astronauts to update in case it exists.
   */
  where: Prisma.AstronautsWhereUniqueInput
  /**
   * In case the Astronauts found by the `where` argument doesn't exist, create a new Astronauts with this data.
   */
  create: Prisma.XOR<Prisma.AstronautsCreateInput, Prisma.AstronautsUncheckedCreateInput>
  /**
   * In case the Astronauts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AstronautsUpdateInput, Prisma.AstronautsUncheckedUpdateInput>
}

/**
 * Astronauts delete
 */
export type AstronautsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
  /**
   * Filter which Astronauts to delete.
   */
  where: Prisma.AstronautsWhereUniqueInput
}

/**
 * Astronauts deleteMany
 */
export type AstronautsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Astronauts to delete
   */
  where?: Prisma.AstronautsWhereInput
  /**
   * Limit how many Astronauts to delete.
   */
  limit?: number
}

/**
 * Astronauts.ownedAstronauts
 */
export type Astronauts$ownedAstronautsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  where?: Prisma.OwnedAstronautsWhereInput
  orderBy?: Prisma.OwnedAstronautsOrderByWithRelationInput | Prisma.OwnedAstronautsOrderByWithRelationInput[]
  cursor?: Prisma.OwnedAstronautsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OwnedAstronautsScalarFieldEnum | Prisma.OwnedAstronautsScalarFieldEnum[]
}

/**
 * Astronauts.unlockedAstronauts
 */
export type Astronauts$unlockedAstronautsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  where?: Prisma.UnlockedAstronautsWhereInput
  orderBy?: Prisma.UnlockedAstronautsOrderByWithRelationInput | Prisma.UnlockedAstronautsOrderByWithRelationInput[]
  cursor?: Prisma.UnlockedAstronautsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.UnlockedAstronautsScalarFieldEnum | Prisma.UnlockedAstronautsScalarFieldEnum[]
}

/**
 * Astronauts without action
 */
export type AstronautsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Astronauts
   */
  select?: Prisma.AstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Astronauts
   */
  omit?: Prisma.AstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AstronautsInclude<ExtArgs> | null
}
