
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OwnedAstronauts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OwnedAstronauts
 * 
 */
export type OwnedAstronautsModel = runtime.Types.Result.DefaultSelection<Prisma.$OwnedAstronautsPayload>

export type AggregateOwnedAstronauts = {
  _count: OwnedAstronautsCountAggregateOutputType | null
  _min: OwnedAstronautsMinAggregateOutputType | null
  _max: OwnedAstronautsMaxAggregateOutputType | null
}

export type OwnedAstronautsMinAggregateOutputType = {
  id: string | null
  ownerName: string | null
  astronautName: string | null
}

export type OwnedAstronautsMaxAggregateOutputType = {
  id: string | null
  ownerName: string | null
  astronautName: string | null
}

export type OwnedAstronautsCountAggregateOutputType = {
  id: number
  ownerName: number
  astronautName: number
  _all: number
}


export type OwnedAstronautsMinAggregateInputType = {
  id?: true
  ownerName?: true
  astronautName?: true
}

export type OwnedAstronautsMaxAggregateInputType = {
  id?: true
  ownerName?: true
  astronautName?: true
}

export type OwnedAstronautsCountAggregateInputType = {
  id?: true
  ownerName?: true
  astronautName?: true
  _all?: true
}

export type OwnedAstronautsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OwnedAstronauts to aggregate.
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwnedAstronauts to fetch.
   */
  orderBy?: Prisma.OwnedAstronautsOrderByWithRelationInput | Prisma.OwnedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OwnedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwnedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwnedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OwnedAstronauts
  **/
  _count?: true | OwnedAstronautsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OwnedAstronautsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OwnedAstronautsMaxAggregateInputType
}

export type GetOwnedAstronautsAggregateType<T extends OwnedAstronautsAggregateArgs> = {
      [P in keyof T & keyof AggregateOwnedAstronauts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOwnedAstronauts[P]>
    : Prisma.GetScalarType<T[P], AggregateOwnedAstronauts[P]>
}




export type OwnedAstronautsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OwnedAstronautsWhereInput
  orderBy?: Prisma.OwnedAstronautsOrderByWithAggregationInput | Prisma.OwnedAstronautsOrderByWithAggregationInput[]
  by: Prisma.OwnedAstronautsScalarFieldEnum[] | Prisma.OwnedAstronautsScalarFieldEnum
  having?: Prisma.OwnedAstronautsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OwnedAstronautsCountAggregateInputType | true
  _min?: OwnedAstronautsMinAggregateInputType
  _max?: OwnedAstronautsMaxAggregateInputType
}

export type OwnedAstronautsGroupByOutputType = {
  id: string
  ownerName: string
  astronautName: string
  _count: OwnedAstronautsCountAggregateOutputType | null
  _min: OwnedAstronautsMinAggregateOutputType | null
  _max: OwnedAstronautsMaxAggregateOutputType | null
}

type GetOwnedAstronautsGroupByPayload<T extends OwnedAstronautsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OwnedAstronautsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OwnedAstronautsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OwnedAstronautsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OwnedAstronautsGroupByOutputType[P]>
      }
    >
  >



export type OwnedAstronautsWhereInput = {
  AND?: Prisma.OwnedAstronautsWhereInput | Prisma.OwnedAstronautsWhereInput[]
  OR?: Prisma.OwnedAstronautsWhereInput[]
  NOT?: Prisma.OwnedAstronautsWhereInput | Prisma.OwnedAstronautsWhereInput[]
  id?: Prisma.StringFilter<"OwnedAstronauts"> | string
  ownerName?: Prisma.StringFilter<"OwnedAstronauts"> | string
  astronautName?: Prisma.StringFilter<"OwnedAstronauts"> | string
  astronautData?: Prisma.XOR<Prisma.AstronautsScalarRelationFilter, Prisma.AstronautsWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type OwnedAstronautsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautName?: Prisma.SortOrder
  astronautData?: Prisma.AstronautsOrderByWithRelationInput
  owner?: Prisma.UserOrderByWithRelationInput
}

export type OwnedAstronautsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.OwnedAstronautsWhereInput | Prisma.OwnedAstronautsWhereInput[]
  OR?: Prisma.OwnedAstronautsWhereInput[]
  NOT?: Prisma.OwnedAstronautsWhereInput | Prisma.OwnedAstronautsWhereInput[]
  ownerName?: Prisma.StringFilter<"OwnedAstronauts"> | string
  astronautName?: Prisma.StringFilter<"OwnedAstronauts"> | string
  astronautData?: Prisma.XOR<Prisma.AstronautsScalarRelationFilter, Prisma.AstronautsWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type OwnedAstronautsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautName?: Prisma.SortOrder
  _count?: Prisma.OwnedAstronautsCountOrderByAggregateInput
  _max?: Prisma.OwnedAstronautsMaxOrderByAggregateInput
  _min?: Prisma.OwnedAstronautsMinOrderByAggregateInput
}

export type OwnedAstronautsScalarWhereWithAggregatesInput = {
  AND?: Prisma.OwnedAstronautsScalarWhereWithAggregatesInput | Prisma.OwnedAstronautsScalarWhereWithAggregatesInput[]
  OR?: Prisma.OwnedAstronautsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OwnedAstronautsScalarWhereWithAggregatesInput | Prisma.OwnedAstronautsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OwnedAstronauts"> | string
  ownerName?: Prisma.StringWithAggregatesFilter<"OwnedAstronauts"> | string
  astronautName?: Prisma.StringWithAggregatesFilter<"OwnedAstronauts"> | string
}

export type OwnedAstronautsCreateInput = {
  id?: string
  astronautData: Prisma.AstronautsCreateNestedOneWithoutOwnedAstronautsInput
  owner: Prisma.UserCreateNestedOneWithoutAstronautsInput
}

export type OwnedAstronautsUncheckedCreateInput = {
  id?: string
  ownerName: string
  astronautName: string
}

export type OwnedAstronautsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  astronautData?: Prisma.AstronautsUpdateOneRequiredWithoutOwnedAstronautsNestedInput
  owner?: Prisma.UserUpdateOneRequiredWithoutAstronautsNestedInput
}

export type OwnedAstronautsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsCreateManyInput = {
  id?: string
  ownerName: string
  astronautName: string
}

export type OwnedAstronautsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsListRelationFilter = {
  every?: Prisma.OwnedAstronautsWhereInput
  some?: Prisma.OwnedAstronautsWhereInput
  none?: Prisma.OwnedAstronautsWhereInput
}

export type OwnedAstronautsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OwnedAstronautsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautName?: Prisma.SortOrder
}

export type OwnedAstronautsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautName?: Prisma.SortOrder
}

export type OwnedAstronautsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautName?: Prisma.SortOrder
}

export type OwnedAstronautsCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.OwnedAstronautsCreateWithoutOwnerInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyOwnerInputEnvelope
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
}

export type OwnedAstronautsUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.OwnedAstronautsCreateWithoutOwnerInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyOwnerInputEnvelope
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
}

export type OwnedAstronautsUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.OwnedAstronautsCreateWithoutOwnerInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutOwnerInput | Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyOwnerInputEnvelope
  set?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  delete?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  update?: Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutOwnerInput | Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.OwnedAstronautsUpdateManyWithWhereWithoutOwnerInput | Prisma.OwnedAstronautsUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
}

export type OwnedAstronautsUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.OwnedAstronautsCreateWithoutOwnerInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.OwnedAstronautsCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutOwnerInput | Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyOwnerInputEnvelope
  set?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  delete?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  update?: Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutOwnerInput | Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.OwnedAstronautsUpdateManyWithWhereWithoutOwnerInput | Prisma.OwnedAstronautsUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
}

export type OwnedAstronautsCreateNestedManyWithoutAstronautDataInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.OwnedAstronautsCreateWithoutAstronautDataInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyAstronautDataInputEnvelope
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
}

export type OwnedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.OwnedAstronautsCreateWithoutAstronautDataInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyAstronautDataInputEnvelope
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
}

export type OwnedAstronautsUpdateManyWithoutAstronautDataNestedInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.OwnedAstronautsCreateWithoutAstronautDataInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  upsert?: Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput | Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyAstronautDataInputEnvelope
  set?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  delete?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  update?: Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput | Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput[]
  updateMany?: Prisma.OwnedAstronautsUpdateManyWithWhereWithoutAstronautDataInput | Prisma.OwnedAstronautsUpdateManyWithWhereWithoutAstronautDataInput[]
  deleteMany?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
}

export type OwnedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput = {
  create?: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.OwnedAstronautsCreateWithoutAstronautDataInput[] | Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.OwnedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  upsert?: Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput | Prisma.OwnedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput[]
  createMany?: Prisma.OwnedAstronautsCreateManyAstronautDataInputEnvelope
  set?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  delete?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  connect?: Prisma.OwnedAstronautsWhereUniqueInput | Prisma.OwnedAstronautsWhereUniqueInput[]
  update?: Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput | Prisma.OwnedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput[]
  updateMany?: Prisma.OwnedAstronautsUpdateManyWithWhereWithoutAstronautDataInput | Prisma.OwnedAstronautsUpdateManyWithWhereWithoutAstronautDataInput[]
  deleteMany?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
}

export type OwnedAstronautsCreateWithoutOwnerInput = {
  id?: string
  astronautData: Prisma.AstronautsCreateNestedOneWithoutOwnedAstronautsInput
}

export type OwnedAstronautsUncheckedCreateWithoutOwnerInput = {
  id?: string
  astronautName: string
}

export type OwnedAstronautsCreateOrConnectWithoutOwnerInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput>
}

export type OwnedAstronautsCreateManyOwnerInputEnvelope = {
  data: Prisma.OwnedAstronautsCreateManyOwnerInput | Prisma.OwnedAstronautsCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type OwnedAstronautsUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  update: Prisma.XOR<Prisma.OwnedAstronautsUpdateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedCreateWithoutOwnerInput>
}

export type OwnedAstronautsUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateWithoutOwnerInput, Prisma.OwnedAstronautsUncheckedUpdateWithoutOwnerInput>
}

export type OwnedAstronautsUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.OwnedAstronautsScalarWhereInput
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateManyMutationInput, Prisma.OwnedAstronautsUncheckedUpdateManyWithoutOwnerInput>
}

export type OwnedAstronautsScalarWhereInput = {
  AND?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
  OR?: Prisma.OwnedAstronautsScalarWhereInput[]
  NOT?: Prisma.OwnedAstronautsScalarWhereInput | Prisma.OwnedAstronautsScalarWhereInput[]
  id?: Prisma.StringFilter<"OwnedAstronauts"> | string
  ownerName?: Prisma.StringFilter<"OwnedAstronauts"> | string
  astronautName?: Prisma.StringFilter<"OwnedAstronauts"> | string
}

export type OwnedAstronautsCreateWithoutAstronautDataInput = {
  id?: string
  owner: Prisma.UserCreateNestedOneWithoutAstronautsInput
}

export type OwnedAstronautsUncheckedCreateWithoutAstronautDataInput = {
  id?: string
  ownerName: string
}

export type OwnedAstronautsCreateOrConnectWithoutAstronautDataInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput>
}

export type OwnedAstronautsCreateManyAstronautDataInputEnvelope = {
  data: Prisma.OwnedAstronautsCreateManyAstronautDataInput | Prisma.OwnedAstronautsCreateManyAstronautDataInput[]
  skipDuplicates?: boolean
}

export type OwnedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  update: Prisma.XOR<Prisma.OwnedAstronautsUpdateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedUpdateWithoutAstronautDataInput>
  create: Prisma.XOR<Prisma.OwnedAstronautsCreateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedCreateWithoutAstronautDataInput>
}

export type OwnedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput = {
  where: Prisma.OwnedAstronautsWhereUniqueInput
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateWithoutAstronautDataInput, Prisma.OwnedAstronautsUncheckedUpdateWithoutAstronautDataInput>
}

export type OwnedAstronautsUpdateManyWithWhereWithoutAstronautDataInput = {
  where: Prisma.OwnedAstronautsScalarWhereInput
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateManyMutationInput, Prisma.OwnedAstronautsUncheckedUpdateManyWithoutAstronautDataInput>
}

export type OwnedAstronautsCreateManyOwnerInput = {
  id?: string
  astronautName: string
}

export type OwnedAstronautsUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  astronautData?: Prisma.AstronautsUpdateOneRequiredWithoutOwnedAstronautsNestedInput
}

export type OwnedAstronautsUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsCreateManyAstronautDataInput = {
  id?: string
  ownerName: string
}

export type OwnedAstronautsUpdateWithoutAstronautDataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  owner?: Prisma.UserUpdateOneRequiredWithoutAstronautsNestedInput
}

export type OwnedAstronautsUncheckedUpdateWithoutAstronautDataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type OwnedAstronautsUncheckedUpdateManyWithoutAstronautDataInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type OwnedAstronautsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerName?: boolean
  astronautName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ownedAstronauts"]>

export type OwnedAstronautsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerName?: boolean
  astronautName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ownedAstronauts"]>

export type OwnedAstronautsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  ownerName?: boolean
  astronautName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ownedAstronauts"]>

export type OwnedAstronautsSelectScalar = {
  id?: boolean
  ownerName?: boolean
  astronautName?: boolean
}

export type OwnedAstronautsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "ownerName" | "astronautName", ExtArgs["result"]["ownedAstronauts"]>
export type OwnedAstronautsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type OwnedAstronautsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type OwnedAstronautsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $OwnedAstronautsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OwnedAstronauts"
  objects: {
    astronautData: Prisma.$AstronautsPayload<ExtArgs>
    owner: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    ownerName: string
    astronautName: string
  }, ExtArgs["result"]["ownedAstronauts"]>
  composites: {}
}

export type OwnedAstronautsGetPayload<S extends boolean | null | undefined | OwnedAstronautsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload, S>

export type OwnedAstronautsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OwnedAstronautsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OwnedAstronautsCountAggregateInputType | true
  }

export interface OwnedAstronautsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OwnedAstronauts'], meta: { name: 'OwnedAstronauts' } }
  /**
   * Find zero or one OwnedAstronauts that matches the filter.
   * @param {OwnedAstronautsFindUniqueArgs} args - Arguments to find a OwnedAstronauts
   * @example
   * // Get one OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OwnedAstronautsFindUniqueArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OwnedAstronauts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OwnedAstronautsFindUniqueOrThrowArgs} args - Arguments to find a OwnedAstronauts
   * @example
   * // Get one OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OwnedAstronautsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OwnedAstronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsFindFirstArgs} args - Arguments to find a OwnedAstronauts
   * @example
   * // Get one OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OwnedAstronautsFindFirstArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsFindFirstArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OwnedAstronauts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsFindFirstOrThrowArgs} args - Arguments to find a OwnedAstronauts
   * @example
   * // Get one OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OwnedAstronautsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OwnedAstronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findMany()
   * 
   * // Get first 10 OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ownedAstronautsWithIdOnly = await prisma.ownedAstronauts.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OwnedAstronautsFindManyArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OwnedAstronauts.
   * @param {OwnedAstronautsCreateArgs} args - Arguments to create a OwnedAstronauts.
   * @example
   * // Create one OwnedAstronauts
   * const OwnedAstronauts = await prisma.ownedAstronauts.create({
   *   data: {
   *     // ... data to create a OwnedAstronauts
   *   }
   * })
   * 
   */
  create<T extends OwnedAstronautsCreateArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsCreateArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OwnedAstronauts.
   * @param {OwnedAstronautsCreateManyArgs} args - Arguments to create many OwnedAstronauts.
   * @example
   * // Create many OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OwnedAstronautsCreateManyArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many OwnedAstronauts and returns the data saved in the database.
   * @param {OwnedAstronautsCreateManyAndReturnArgs} args - Arguments to create many OwnedAstronauts.
   * @example
   * // Create many OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many OwnedAstronauts and only return the `id`
   * const ownedAstronautsWithIdOnly = await prisma.ownedAstronauts.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OwnedAstronautsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a OwnedAstronauts.
   * @param {OwnedAstronautsDeleteArgs} args - Arguments to delete one OwnedAstronauts.
   * @example
   * // Delete one OwnedAstronauts
   * const OwnedAstronauts = await prisma.ownedAstronauts.delete({
   *   where: {
   *     // ... filter to delete one OwnedAstronauts
   *   }
   * })
   * 
   */
  delete<T extends OwnedAstronautsDeleteArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsDeleteArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OwnedAstronauts.
   * @param {OwnedAstronautsUpdateArgs} args - Arguments to update one OwnedAstronauts.
   * @example
   * // Update one OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OwnedAstronautsUpdateArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsUpdateArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OwnedAstronauts.
   * @param {OwnedAstronautsDeleteManyArgs} args - Arguments to filter OwnedAstronauts to delete.
   * @example
   * // Delete a few OwnedAstronauts
   * const { count } = await prisma.ownedAstronauts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OwnedAstronautsDeleteManyArgs>(args?: Prisma.SelectSubset<T, OwnedAstronautsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OwnedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OwnedAstronautsUpdateManyArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OwnedAstronauts and returns the data updated in the database.
   * @param {OwnedAstronautsUpdateManyAndReturnArgs} args - Arguments to update many OwnedAstronauts.
   * @example
   * // Update many OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more OwnedAstronauts and only return the `id`
   * const ownedAstronautsWithIdOnly = await prisma.ownedAstronauts.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OwnedAstronautsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one OwnedAstronauts.
   * @param {OwnedAstronautsUpsertArgs} args - Arguments to update or create a OwnedAstronauts.
   * @example
   * // Update or create a OwnedAstronauts
   * const ownedAstronauts = await prisma.ownedAstronauts.upsert({
   *   create: {
   *     // ... data to create a OwnedAstronauts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OwnedAstronauts we want to update
   *   }
   * })
   */
  upsert<T extends OwnedAstronautsUpsertArgs>(args: Prisma.SelectSubset<T, OwnedAstronautsUpsertArgs<ExtArgs>>): Prisma.Prisma__OwnedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$OwnedAstronautsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OwnedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsCountArgs} args - Arguments to filter OwnedAstronauts to count.
   * @example
   * // Count the number of OwnedAstronauts
   * const count = await prisma.ownedAstronauts.count({
   *   where: {
   *     // ... the filter for the OwnedAstronauts we want to count
   *   }
   * })
  **/
  count<T extends OwnedAstronautsCountArgs>(
    args?: Prisma.Subset<T, OwnedAstronautsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OwnedAstronautsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OwnedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OwnedAstronautsAggregateArgs>(args: Prisma.Subset<T, OwnedAstronautsAggregateArgs>): Prisma.PrismaPromise<GetOwnedAstronautsAggregateType<T>>

  /**
   * Group by OwnedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OwnedAstronautsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OwnedAstronautsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OwnedAstronautsGroupByArgs['orderBy'] }
      : { orderBy?: OwnedAstronautsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OwnedAstronautsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOwnedAstronautsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OwnedAstronauts model
 */
readonly fields: OwnedAstronautsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OwnedAstronauts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OwnedAstronautsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  astronautData<T extends Prisma.AstronautsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AstronautsDefaultArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OwnedAstronauts model
 */
export interface OwnedAstronautsFieldRefs {
  readonly id: Prisma.FieldRef<"OwnedAstronauts", 'String'>
  readonly ownerName: Prisma.FieldRef<"OwnedAstronauts", 'String'>
  readonly astronautName: Prisma.FieldRef<"OwnedAstronauts", 'String'>
}
    

// Custom InputTypes
/**
 * OwnedAstronauts findUnique
 */
export type OwnedAstronautsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which OwnedAstronauts to fetch.
   */
  where: Prisma.OwnedAstronautsWhereUniqueInput
}

/**
 * OwnedAstronauts findUniqueOrThrow
 */
export type OwnedAstronautsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which OwnedAstronauts to fetch.
   */
  where: Prisma.OwnedAstronautsWhereUniqueInput
}

/**
 * OwnedAstronauts findFirst
 */
export type OwnedAstronautsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which OwnedAstronauts to fetch.
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwnedAstronauts to fetch.
   */
  orderBy?: Prisma.OwnedAstronautsOrderByWithRelationInput | Prisma.OwnedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OwnedAstronauts.
   */
  cursor?: Prisma.OwnedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwnedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwnedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OwnedAstronauts.
   */
  distinct?: Prisma.OwnedAstronautsScalarFieldEnum | Prisma.OwnedAstronautsScalarFieldEnum[]
}

/**
 * OwnedAstronauts findFirstOrThrow
 */
export type OwnedAstronautsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which OwnedAstronauts to fetch.
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwnedAstronauts to fetch.
   */
  orderBy?: Prisma.OwnedAstronautsOrderByWithRelationInput | Prisma.OwnedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OwnedAstronauts.
   */
  cursor?: Prisma.OwnedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwnedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwnedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OwnedAstronauts.
   */
  distinct?: Prisma.OwnedAstronautsScalarFieldEnum | Prisma.OwnedAstronautsScalarFieldEnum[]
}

/**
 * OwnedAstronauts findMany
 */
export type OwnedAstronautsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which OwnedAstronauts to fetch.
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OwnedAstronauts to fetch.
   */
  orderBy?: Prisma.OwnedAstronautsOrderByWithRelationInput | Prisma.OwnedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OwnedAstronauts.
   */
  cursor?: Prisma.OwnedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OwnedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OwnedAstronauts.
   */
  skip?: number
  distinct?: Prisma.OwnedAstronautsScalarFieldEnum | Prisma.OwnedAstronautsScalarFieldEnum[]
}

/**
 * OwnedAstronauts create
 */
export type OwnedAstronautsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * The data needed to create a OwnedAstronauts.
   */
  data: Prisma.XOR<Prisma.OwnedAstronautsCreateInput, Prisma.OwnedAstronautsUncheckedCreateInput>
}

/**
 * OwnedAstronauts createMany
 */
export type OwnedAstronautsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OwnedAstronauts.
   */
  data: Prisma.OwnedAstronautsCreateManyInput | Prisma.OwnedAstronautsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OwnedAstronauts createManyAndReturn
 */
export type OwnedAstronautsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * The data used to create many OwnedAstronauts.
   */
  data: Prisma.OwnedAstronautsCreateManyInput | Prisma.OwnedAstronautsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * OwnedAstronauts update
 */
export type OwnedAstronautsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * The data needed to update a OwnedAstronauts.
   */
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateInput, Prisma.OwnedAstronautsUncheckedUpdateInput>
  /**
   * Choose, which OwnedAstronauts to update.
   */
  where: Prisma.OwnedAstronautsWhereUniqueInput
}

/**
 * OwnedAstronauts updateMany
 */
export type OwnedAstronautsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OwnedAstronauts.
   */
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateManyMutationInput, Prisma.OwnedAstronautsUncheckedUpdateManyInput>
  /**
   * Filter which OwnedAstronauts to update
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * Limit how many OwnedAstronauts to update.
   */
  limit?: number
}

/**
 * OwnedAstronauts updateManyAndReturn
 */
export type OwnedAstronautsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * The data used to update OwnedAstronauts.
   */
  data: Prisma.XOR<Prisma.OwnedAstronautsUpdateManyMutationInput, Prisma.OwnedAstronautsUncheckedUpdateManyInput>
  /**
   * Filter which OwnedAstronauts to update
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * Limit how many OwnedAstronauts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * OwnedAstronauts upsert
 */
export type OwnedAstronautsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * The filter to search for the OwnedAstronauts to update in case it exists.
   */
  where: Prisma.OwnedAstronautsWhereUniqueInput
  /**
   * In case the OwnedAstronauts found by the `where` argument doesn't exist, create a new OwnedAstronauts with this data.
   */
  create: Prisma.XOR<Prisma.OwnedAstronautsCreateInput, Prisma.OwnedAstronautsUncheckedCreateInput>
  /**
   * In case the OwnedAstronauts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OwnedAstronautsUpdateInput, Prisma.OwnedAstronautsUncheckedUpdateInput>
}

/**
 * OwnedAstronauts delete
 */
export type OwnedAstronautsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
  /**
   * Filter which OwnedAstronauts to delete.
   */
  where: Prisma.OwnedAstronautsWhereUniqueInput
}

/**
 * OwnedAstronauts deleteMany
 */
export type OwnedAstronautsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OwnedAstronauts to delete
   */
  where?: Prisma.OwnedAstronautsWhereInput
  /**
   * Limit how many OwnedAstronauts to delete.
   */
  limit?: number
}

/**
 * OwnedAstronauts without action
 */
export type OwnedAstronautsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OwnedAstronauts
   */
  select?: Prisma.OwnedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OwnedAstronauts
   */
  omit?: Prisma.OwnedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OwnedAstronautsInclude<ExtArgs> | null
}
