
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `UnlockedAstronauts` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model UnlockedAstronauts
 * 
 */
export type UnlockedAstronautsModel = runtime.Types.Result.DefaultSelection<Prisma.$UnlockedAstronautsPayload>

export type AggregateUnlockedAstronauts = {
  _count: UnlockedAstronautsCountAggregateOutputType | null
  _min: UnlockedAstronautsMinAggregateOutputType | null
  _max: UnlockedAstronautsMaxAggregateOutputType | null
}

export type UnlockedAstronautsMinAggregateOutputType = {
  astronautName: string | null
  ownerName: string | null
}

export type UnlockedAstronautsMaxAggregateOutputType = {
  astronautName: string | null
  ownerName: string | null
}

export type UnlockedAstronautsCountAggregateOutputType = {
  astronautName: number
  ownerName: number
  _all: number
}


export type UnlockedAstronautsMinAggregateInputType = {
  astronautName?: true
  ownerName?: true
}

export type UnlockedAstronautsMaxAggregateInputType = {
  astronautName?: true
  ownerName?: true
}

export type UnlockedAstronautsCountAggregateInputType = {
  astronautName?: true
  ownerName?: true
  _all?: true
}

export type UnlockedAstronautsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnlockedAstronauts to aggregate.
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedAstronauts to fetch.
   */
  orderBy?: Prisma.UnlockedAstronautsOrderByWithRelationInput | Prisma.UnlockedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UnlockedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned UnlockedAstronauts
  **/
  _count?: true | UnlockedAstronautsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UnlockedAstronautsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UnlockedAstronautsMaxAggregateInputType
}

export type GetUnlockedAstronautsAggregateType<T extends UnlockedAstronautsAggregateArgs> = {
      [P in keyof T & keyof AggregateUnlockedAstronauts]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUnlockedAstronauts[P]>
    : Prisma.GetScalarType<T[P], AggregateUnlockedAstronauts[P]>
}




export type UnlockedAstronautsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UnlockedAstronautsWhereInput
  orderBy?: Prisma.UnlockedAstronautsOrderByWithAggregationInput | Prisma.UnlockedAstronautsOrderByWithAggregationInput[]
  by: Prisma.UnlockedAstronautsScalarFieldEnum[] | Prisma.UnlockedAstronautsScalarFieldEnum
  having?: Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UnlockedAstronautsCountAggregateInputType | true
  _min?: UnlockedAstronautsMinAggregateInputType
  _max?: UnlockedAstronautsMaxAggregateInputType
}

export type UnlockedAstronautsGroupByOutputType = {
  astronautName: string
  ownerName: string
  _count: UnlockedAstronautsCountAggregateOutputType | null
  _min: UnlockedAstronautsMinAggregateOutputType | null
  _max: UnlockedAstronautsMaxAggregateOutputType | null
}

type GetUnlockedAstronautsGroupByPayload<T extends UnlockedAstronautsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UnlockedAstronautsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UnlockedAstronautsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UnlockedAstronautsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UnlockedAstronautsGroupByOutputType[P]>
      }
    >
  >



export type UnlockedAstronautsWhereInput = {
  AND?: Prisma.UnlockedAstronautsWhereInput | Prisma.UnlockedAstronautsWhereInput[]
  OR?: Prisma.UnlockedAstronautsWhereInput[]
  NOT?: Prisma.UnlockedAstronautsWhereInput | Prisma.UnlockedAstronautsWhereInput[]
  astronautName?: Prisma.StringFilter<"UnlockedAstronauts"> | string
  ownerName?: Prisma.StringFilter<"UnlockedAstronauts"> | string
  astronautData?: Prisma.XOR<Prisma.AstronautsScalarRelationFilter, Prisma.AstronautsWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type UnlockedAstronautsOrderByWithRelationInput = {
  astronautName?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  astronautData?: Prisma.AstronautsOrderByWithRelationInput
  owner?: Prisma.UserOrderByWithRelationInput
}

export type UnlockedAstronautsWhereUniqueInput = Prisma.AtLeast<{
  astronautName?: string
  AND?: Prisma.UnlockedAstronautsWhereInput | Prisma.UnlockedAstronautsWhereInput[]
  OR?: Prisma.UnlockedAstronautsWhereInput[]
  NOT?: Prisma.UnlockedAstronautsWhereInput | Prisma.UnlockedAstronautsWhereInput[]
  ownerName?: Prisma.StringFilter<"UnlockedAstronauts"> | string
  astronautData?: Prisma.XOR<Prisma.AstronautsScalarRelationFilter, Prisma.AstronautsWhereInput>
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "astronautName">

export type UnlockedAstronautsOrderByWithAggregationInput = {
  astronautName?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
  _count?: Prisma.UnlockedAstronautsCountOrderByAggregateInput
  _max?: Prisma.UnlockedAstronautsMaxOrderByAggregateInput
  _min?: Prisma.UnlockedAstronautsMinOrderByAggregateInput
}

export type UnlockedAstronautsScalarWhereWithAggregatesInput = {
  AND?: Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput | Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput[]
  OR?: Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput | Prisma.UnlockedAstronautsScalarWhereWithAggregatesInput[]
  astronautName?: Prisma.StringWithAggregatesFilter<"UnlockedAstronauts"> | string
  ownerName?: Prisma.StringWithAggregatesFilter<"UnlockedAstronauts"> | string
}

export type UnlockedAstronautsCreateInput = {
  astronautData: Prisma.AstronautsCreateNestedOneWithoutUnlockedAstronautsInput
  owner: Prisma.UserCreateNestedOneWithoutUnlockedAstronautsInput
}

export type UnlockedAstronautsUncheckedCreateInput = {
  astronautName: string
  ownerName: string
}

export type UnlockedAstronautsUpdateInput = {
  astronautData?: Prisma.AstronautsUpdateOneRequiredWithoutUnlockedAstronautsNestedInput
  owner?: Prisma.UserUpdateOneRequiredWithoutUnlockedAstronautsNestedInput
}

export type UnlockedAstronautsUncheckedUpdateInput = {
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnlockedAstronautsCreateManyInput = {
  astronautName: string
  ownerName: string
}

export type UnlockedAstronautsUpdateManyMutationInput = {

}

export type UnlockedAstronautsUncheckedUpdateManyInput = {
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnlockedAstronautsListRelationFilter = {
  every?: Prisma.UnlockedAstronautsWhereInput
  some?: Prisma.UnlockedAstronautsWhereInput
  none?: Prisma.UnlockedAstronautsWhereInput
}

export type UnlockedAstronautsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UnlockedAstronautsCountOrderByAggregateInput = {
  astronautName?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
}

export type UnlockedAstronautsMaxOrderByAggregateInput = {
  astronautName?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
}

export type UnlockedAstronautsMinOrderByAggregateInput = {
  astronautName?: Prisma.SortOrder
  ownerName?: Prisma.SortOrder
}

export type UnlockedAstronautsCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.UnlockedAstronautsCreateWithoutOwnerInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyOwnerInputEnvelope
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
}

export type UnlockedAstronautsUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.UnlockedAstronautsCreateWithoutOwnerInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyOwnerInputEnvelope
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
}

export type UnlockedAstronautsUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.UnlockedAstronautsCreateWithoutOwnerInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutOwnerInput | Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyOwnerInputEnvelope
  set?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  delete?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  update?: Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutOwnerInput | Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutOwnerInput | Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
}

export type UnlockedAstronautsUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput> | Prisma.UnlockedAstronautsCreateWithoutOwnerInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutOwnerInput | Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyOwnerInputEnvelope
  set?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  delete?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  update?: Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutOwnerInput | Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutOwnerInput | Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
}

export type UnlockedAstronautsCreateNestedManyWithoutAstronautDataInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyAstronautDataInputEnvelope
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
}

export type UnlockedAstronautsUncheckedCreateNestedManyWithoutAstronautDataInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyAstronautDataInputEnvelope
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
}

export type UnlockedAstronautsUpdateManyWithoutAstronautDataNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  upsert?: Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyAstronautDataInputEnvelope
  set?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  delete?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  update?: Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput[]
  updateMany?: Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutAstronautDataInput[]
  deleteMany?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
}

export type UnlockedAstronautsUncheckedUpdateManyWithoutAstronautDataNestedInput = {
  create?: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput> | Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput[] | Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput[]
  connectOrCreate?: Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput | Prisma.UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput[]
  upsert?: Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput[]
  createMany?: Prisma.UnlockedAstronautsCreateManyAstronautDataInputEnvelope
  set?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  disconnect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  delete?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  connect?: Prisma.UnlockedAstronautsWhereUniqueInput | Prisma.UnlockedAstronautsWhereUniqueInput[]
  update?: Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput[]
  updateMany?: Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutAstronautDataInput | Prisma.UnlockedAstronautsUpdateManyWithWhereWithoutAstronautDataInput[]
  deleteMany?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
}

export type UnlockedAstronautsCreateWithoutOwnerInput = {
  astronautData: Prisma.AstronautsCreateNestedOneWithoutUnlockedAstronautsInput
}

export type UnlockedAstronautsUncheckedCreateWithoutOwnerInput = {
  astronautName: string
}

export type UnlockedAstronautsCreateOrConnectWithoutOwnerInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput>
}

export type UnlockedAstronautsCreateManyOwnerInputEnvelope = {
  data: Prisma.UnlockedAstronautsCreateManyOwnerInput | Prisma.UnlockedAstronautsCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type UnlockedAstronautsUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  update: Prisma.XOR<Prisma.UnlockedAstronautsUpdateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutOwnerInput>
}

export type UnlockedAstronautsUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateWithoutOwnerInput, Prisma.UnlockedAstronautsUncheckedUpdateWithoutOwnerInput>
}

export type UnlockedAstronautsUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.UnlockedAstronautsScalarWhereInput
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateManyMutationInput, Prisma.UnlockedAstronautsUncheckedUpdateManyWithoutOwnerInput>
}

export type UnlockedAstronautsScalarWhereInput = {
  AND?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
  OR?: Prisma.UnlockedAstronautsScalarWhereInput[]
  NOT?: Prisma.UnlockedAstronautsScalarWhereInput | Prisma.UnlockedAstronautsScalarWhereInput[]
  astronautName?: Prisma.StringFilter<"UnlockedAstronauts"> | string
  ownerName?: Prisma.StringFilter<"UnlockedAstronauts"> | string
}

export type UnlockedAstronautsCreateWithoutAstronautDataInput = {
  owner: Prisma.UserCreateNestedOneWithoutUnlockedAstronautsInput
}

export type UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput = {
  ownerName: string
}

export type UnlockedAstronautsCreateOrConnectWithoutAstronautDataInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  create: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput>
}

export type UnlockedAstronautsCreateManyAstronautDataInputEnvelope = {
  data: Prisma.UnlockedAstronautsCreateManyAstronautDataInput | Prisma.UnlockedAstronautsCreateManyAstronautDataInput[]
  skipDuplicates?: boolean
}

export type UnlockedAstronautsUpsertWithWhereUniqueWithoutAstronautDataInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  update: Prisma.XOR<Prisma.UnlockedAstronautsUpdateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedUpdateWithoutAstronautDataInput>
  create: Prisma.XOR<Prisma.UnlockedAstronautsCreateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedCreateWithoutAstronautDataInput>
}

export type UnlockedAstronautsUpdateWithWhereUniqueWithoutAstronautDataInput = {
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateWithoutAstronautDataInput, Prisma.UnlockedAstronautsUncheckedUpdateWithoutAstronautDataInput>
}

export type UnlockedAstronautsUpdateManyWithWhereWithoutAstronautDataInput = {
  where: Prisma.UnlockedAstronautsScalarWhereInput
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateManyMutationInput, Prisma.UnlockedAstronautsUncheckedUpdateManyWithoutAstronautDataInput>
}

export type UnlockedAstronautsCreateManyOwnerInput = {
  astronautName: string
}

export type UnlockedAstronautsUpdateWithoutOwnerInput = {
  astronautData?: Prisma.AstronautsUpdateOneRequiredWithoutUnlockedAstronautsNestedInput
}

export type UnlockedAstronautsUncheckedUpdateWithoutOwnerInput = {
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnlockedAstronautsUncheckedUpdateManyWithoutOwnerInput = {
  astronautName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnlockedAstronautsCreateManyAstronautDataInput = {
  ownerName: string
}

export type UnlockedAstronautsUpdateWithoutAstronautDataInput = {
  owner?: Prisma.UserUpdateOneRequiredWithoutUnlockedAstronautsNestedInput
}

export type UnlockedAstronautsUncheckedUpdateWithoutAstronautDataInput = {
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}

export type UnlockedAstronautsUncheckedUpdateManyWithoutAstronautDataInput = {
  ownerName?: Prisma.StringFieldUpdateOperationsInput | string
}



export type UnlockedAstronautsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  astronautName?: boolean
  ownerName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedAstronauts"]>

export type UnlockedAstronautsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  astronautName?: boolean
  ownerName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedAstronauts"]>

export type UnlockedAstronautsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  astronautName?: boolean
  ownerName?: boolean
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["unlockedAstronauts"]>

export type UnlockedAstronautsSelectScalar = {
  astronautName?: boolean
  ownerName?: boolean
}

export type UnlockedAstronautsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"astronautName" | "ownerName", ExtArgs["result"]["unlockedAstronauts"]>
export type UnlockedAstronautsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UnlockedAstronautsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type UnlockedAstronautsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  astronautData?: boolean | Prisma.AstronautsDefaultArgs<ExtArgs>
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $UnlockedAstronautsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "UnlockedAstronauts"
  objects: {
    astronautData: Prisma.$AstronautsPayload<ExtArgs>
    owner: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    astronautName: string
    ownerName: string
  }, ExtArgs["result"]["unlockedAstronauts"]>
  composites: {}
}

export type UnlockedAstronautsGetPayload<S extends boolean | null | undefined | UnlockedAstronautsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload, S>

export type UnlockedAstronautsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UnlockedAstronautsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UnlockedAstronautsCountAggregateInputType | true
  }

export interface UnlockedAstronautsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['UnlockedAstronauts'], meta: { name: 'UnlockedAstronauts' } }
  /**
   * Find zero or one UnlockedAstronauts that matches the filter.
   * @param {UnlockedAstronautsFindUniqueArgs} args - Arguments to find a UnlockedAstronauts
   * @example
   * // Get one UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UnlockedAstronautsFindUniqueArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one UnlockedAstronauts that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UnlockedAstronautsFindUniqueOrThrowArgs} args - Arguments to find a UnlockedAstronauts
   * @example
   * // Get one UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UnlockedAstronautsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnlockedAstronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsFindFirstArgs} args - Arguments to find a UnlockedAstronauts
   * @example
   * // Get one UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UnlockedAstronautsFindFirstArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsFindFirstArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first UnlockedAstronauts that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsFindFirstOrThrowArgs} args - Arguments to find a UnlockedAstronauts
   * @example
   * // Get one UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UnlockedAstronautsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more UnlockedAstronauts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findMany()
   * 
   * // Get first 10 UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.findMany({ take: 10 })
   * 
   * // Only select the `astronautName`
   * const unlockedAstronautsWithAstronautNameOnly = await prisma.unlockedAstronauts.findMany({ select: { astronautName: true } })
   * 
   */
  findMany<T extends UnlockedAstronautsFindManyArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a UnlockedAstronauts.
   * @param {UnlockedAstronautsCreateArgs} args - Arguments to create a UnlockedAstronauts.
   * @example
   * // Create one UnlockedAstronauts
   * const UnlockedAstronauts = await prisma.unlockedAstronauts.create({
   *   data: {
   *     // ... data to create a UnlockedAstronauts
   *   }
   * })
   * 
   */
  create<T extends UnlockedAstronautsCreateArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsCreateArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many UnlockedAstronauts.
   * @param {UnlockedAstronautsCreateManyArgs} args - Arguments to create many UnlockedAstronauts.
   * @example
   * // Create many UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UnlockedAstronautsCreateManyArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many UnlockedAstronauts and returns the data saved in the database.
   * @param {UnlockedAstronautsCreateManyAndReturnArgs} args - Arguments to create many UnlockedAstronauts.
   * @example
   * // Create many UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many UnlockedAstronauts and only return the `astronautName`
   * const unlockedAstronautsWithAstronautNameOnly = await prisma.unlockedAstronauts.createManyAndReturn({
   *   select: { astronautName: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UnlockedAstronautsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a UnlockedAstronauts.
   * @param {UnlockedAstronautsDeleteArgs} args - Arguments to delete one UnlockedAstronauts.
   * @example
   * // Delete one UnlockedAstronauts
   * const UnlockedAstronauts = await prisma.unlockedAstronauts.delete({
   *   where: {
   *     // ... filter to delete one UnlockedAstronauts
   *   }
   * })
   * 
   */
  delete<T extends UnlockedAstronautsDeleteArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsDeleteArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one UnlockedAstronauts.
   * @param {UnlockedAstronautsUpdateArgs} args - Arguments to update one UnlockedAstronauts.
   * @example
   * // Update one UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UnlockedAstronautsUpdateArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsUpdateArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more UnlockedAstronauts.
   * @param {UnlockedAstronautsDeleteManyArgs} args - Arguments to filter UnlockedAstronauts to delete.
   * @example
   * // Delete a few UnlockedAstronauts
   * const { count } = await prisma.unlockedAstronauts.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UnlockedAstronautsDeleteManyArgs>(args?: Prisma.SelectSubset<T, UnlockedAstronautsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnlockedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UnlockedAstronautsUpdateManyArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more UnlockedAstronauts and returns the data updated in the database.
   * @param {UnlockedAstronautsUpdateManyAndReturnArgs} args - Arguments to update many UnlockedAstronauts.
   * @example
   * // Update many UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more UnlockedAstronauts and only return the `astronautName`
   * const unlockedAstronautsWithAstronautNameOnly = await prisma.unlockedAstronauts.updateManyAndReturn({
   *   select: { astronautName: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UnlockedAstronautsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one UnlockedAstronauts.
   * @param {UnlockedAstronautsUpsertArgs} args - Arguments to update or create a UnlockedAstronauts.
   * @example
   * // Update or create a UnlockedAstronauts
   * const unlockedAstronauts = await prisma.unlockedAstronauts.upsert({
   *   create: {
   *     // ... data to create a UnlockedAstronauts
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the UnlockedAstronauts we want to update
   *   }
   * })
   */
  upsert<T extends UnlockedAstronautsUpsertArgs>(args: Prisma.SelectSubset<T, UnlockedAstronautsUpsertArgs<ExtArgs>>): Prisma.Prisma__UnlockedAstronautsClient<runtime.Types.Result.GetResult<Prisma.$UnlockedAstronautsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of UnlockedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsCountArgs} args - Arguments to filter UnlockedAstronauts to count.
   * @example
   * // Count the number of UnlockedAstronauts
   * const count = await prisma.unlockedAstronauts.count({
   *   where: {
   *     // ... the filter for the UnlockedAstronauts we want to count
   *   }
   * })
  **/
  count<T extends UnlockedAstronautsCountArgs>(
    args?: Prisma.Subset<T, UnlockedAstronautsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UnlockedAstronautsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a UnlockedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UnlockedAstronautsAggregateArgs>(args: Prisma.Subset<T, UnlockedAstronautsAggregateArgs>): Prisma.PrismaPromise<GetUnlockedAstronautsAggregateType<T>>

  /**
   * Group by UnlockedAstronauts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UnlockedAstronautsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UnlockedAstronautsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UnlockedAstronautsGroupByArgs['orderBy'] }
      : { orderBy?: UnlockedAstronautsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UnlockedAstronautsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUnlockedAstronautsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the UnlockedAstronauts model
 */
readonly fields: UnlockedAstronautsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for UnlockedAstronauts.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UnlockedAstronautsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  astronautData<T extends Prisma.AstronautsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AstronautsDefaultArgs<ExtArgs>>): Prisma.Prisma__AstronautsClient<runtime.Types.Result.GetResult<Prisma.$AstronautsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the UnlockedAstronauts model
 */
export interface UnlockedAstronautsFieldRefs {
  readonly astronautName: Prisma.FieldRef<"UnlockedAstronauts", 'String'>
  readonly ownerName: Prisma.FieldRef<"UnlockedAstronauts", 'String'>
}
    

// Custom InputTypes
/**
 * UnlockedAstronauts findUnique
 */
export type UnlockedAstronautsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedAstronauts to fetch.
   */
  where: Prisma.UnlockedAstronautsWhereUniqueInput
}

/**
 * UnlockedAstronauts findUniqueOrThrow
 */
export type UnlockedAstronautsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedAstronauts to fetch.
   */
  where: Prisma.UnlockedAstronautsWhereUniqueInput
}

/**
 * UnlockedAstronauts findFirst
 */
export type UnlockedAstronautsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedAstronauts to fetch.
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedAstronauts to fetch.
   */
  orderBy?: Prisma.UnlockedAstronautsOrderByWithRelationInput | Prisma.UnlockedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnlockedAstronauts.
   */
  cursor?: Prisma.UnlockedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnlockedAstronauts.
   */
  distinct?: Prisma.UnlockedAstronautsScalarFieldEnum | Prisma.UnlockedAstronautsScalarFieldEnum[]
}

/**
 * UnlockedAstronauts findFirstOrThrow
 */
export type UnlockedAstronautsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedAstronauts to fetch.
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedAstronauts to fetch.
   */
  orderBy?: Prisma.UnlockedAstronautsOrderByWithRelationInput | Prisma.UnlockedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for UnlockedAstronauts.
   */
  cursor?: Prisma.UnlockedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedAstronauts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of UnlockedAstronauts.
   */
  distinct?: Prisma.UnlockedAstronautsScalarFieldEnum | Prisma.UnlockedAstronautsScalarFieldEnum[]
}

/**
 * UnlockedAstronauts findMany
 */
export type UnlockedAstronautsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter, which UnlockedAstronauts to fetch.
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of UnlockedAstronauts to fetch.
   */
  orderBy?: Prisma.UnlockedAstronautsOrderByWithRelationInput | Prisma.UnlockedAstronautsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing UnlockedAstronauts.
   */
  cursor?: Prisma.UnlockedAstronautsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` UnlockedAstronauts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` UnlockedAstronauts.
   */
  skip?: number
  distinct?: Prisma.UnlockedAstronautsScalarFieldEnum | Prisma.UnlockedAstronautsScalarFieldEnum[]
}

/**
 * UnlockedAstronauts create
 */
export type UnlockedAstronautsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * The data needed to create a UnlockedAstronauts.
   */
  data: Prisma.XOR<Prisma.UnlockedAstronautsCreateInput, Prisma.UnlockedAstronautsUncheckedCreateInput>
}

/**
 * UnlockedAstronauts createMany
 */
export type UnlockedAstronautsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many UnlockedAstronauts.
   */
  data: Prisma.UnlockedAstronautsCreateManyInput | Prisma.UnlockedAstronautsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * UnlockedAstronauts createManyAndReturn
 */
export type UnlockedAstronautsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * The data used to create many UnlockedAstronauts.
   */
  data: Prisma.UnlockedAstronautsCreateManyInput | Prisma.UnlockedAstronautsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * UnlockedAstronauts update
 */
export type UnlockedAstronautsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * The data needed to update a UnlockedAstronauts.
   */
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateInput, Prisma.UnlockedAstronautsUncheckedUpdateInput>
  /**
   * Choose, which UnlockedAstronauts to update.
   */
  where: Prisma.UnlockedAstronautsWhereUniqueInput
}

/**
 * UnlockedAstronauts updateMany
 */
export type UnlockedAstronautsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update UnlockedAstronauts.
   */
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateManyMutationInput, Prisma.UnlockedAstronautsUncheckedUpdateManyInput>
  /**
   * Filter which UnlockedAstronauts to update
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * Limit how many UnlockedAstronauts to update.
   */
  limit?: number
}

/**
 * UnlockedAstronauts updateManyAndReturn
 */
export type UnlockedAstronautsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * The data used to update UnlockedAstronauts.
   */
  data: Prisma.XOR<Prisma.UnlockedAstronautsUpdateManyMutationInput, Prisma.UnlockedAstronautsUncheckedUpdateManyInput>
  /**
   * Filter which UnlockedAstronauts to update
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * Limit how many UnlockedAstronauts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * UnlockedAstronauts upsert
 */
export type UnlockedAstronautsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * The filter to search for the UnlockedAstronauts to update in case it exists.
   */
  where: Prisma.UnlockedAstronautsWhereUniqueInput
  /**
   * In case the UnlockedAstronauts found by the `where` argument doesn't exist, create a new UnlockedAstronauts with this data.
   */
  create: Prisma.XOR<Prisma.UnlockedAstronautsCreateInput, Prisma.UnlockedAstronautsUncheckedCreateInput>
  /**
   * In case the UnlockedAstronauts was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UnlockedAstronautsUpdateInput, Prisma.UnlockedAstronautsUncheckedUpdateInput>
}

/**
 * UnlockedAstronauts delete
 */
export type UnlockedAstronautsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
  /**
   * Filter which UnlockedAstronauts to delete.
   */
  where: Prisma.UnlockedAstronautsWhereUniqueInput
}

/**
 * UnlockedAstronauts deleteMany
 */
export type UnlockedAstronautsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which UnlockedAstronauts to delete
   */
  where?: Prisma.UnlockedAstronautsWhereInput
  /**
   * Limit how many UnlockedAstronauts to delete.
   */
  limit?: number
}

/**
 * UnlockedAstronauts without action
 */
export type UnlockedAstronautsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UnlockedAstronauts
   */
  select?: Prisma.UnlockedAstronautsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the UnlockedAstronauts
   */
  omit?: Prisma.UnlockedAstronautsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UnlockedAstronautsInclude<ExtArgs> | null
}
